version: '3.9'

services:
  mongodb:
    restart: unless-stopped
    image: docker.io/bitnami/mongodb:7.0.5
    container_name: torrentio-mongodb
    environment: 
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/bitnami/mongodb
    networks:
      - saltbox

  scraper:
    build: ./scraper
    container_name: torrentio-scraper

    depends_on:
      - mongodb
      - postgres
    restart: unless-stopped
    ports:
      - "7001:7001"
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
    networks:
      - saltbox

  torrentio:
    build: ./addon
    container_name: torrentio
    depends_on:
      - mongodb
      - postgres
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - PUID=1000
      - PGID=1000
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
    networks: 
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true 
      traefik.enable: true 
      traefik.http.routers.torrentio-http.entrypoints: web 
      traefik.http.routers.torrentio-http.middlewares: globalHeaders@file,redirect-to-https@docker,cloudflarewarp@docker 
      traefik.http.routers.torrentio-http.rule: Host(`torrentio.domain.com`) 
      traefik.http.routers.torrentio-http.service: torrentio 
      traefik.http.routers.torrentio.entrypoints: websecure 
      traefik.http.routers.torrentio.middlewares: globalHeaders@file,secureHeaders@file,cloudflarewarp@docker 
      traefik.http.routers.torrentio.rule: Host(`torrentio.domain.com`) 
      traefik.http.routers.torrentio.service: torrentio 
      traefik.http.routers.torrentio.tls.certresolver: cfdns 
      traefik.http.routers.torrentio.tls.options: securetls@file 
      traefik.http.services.torrentio.loadbalancer.server.port: 7000

  postgres:
    image: postgres:14-alpine
    container_name: torrentio-pgdb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /opt/torrentio-sh/pg_data:/var/lib/postgresql/data
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio
    networks: 
      - saltbox

networks: 
  saltbox:
    external: true

volumes:
  mongo-data:
